{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "stats.gauges.temperature" }
   ]
  },
  {
   "title": "Température",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.gauges.temperature" }
   ]
  },
  {
   "title": "Requests/s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "target": "stats_counts.numberOfRequests" }
   ]
  },
  {
   "title": "Highest Temp",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "format": "celsius",
   "valueName": "max",
   "targets": [
    { "target": "stats.gauges.temperature" }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.http.post.workshop.response_time.mean"
    }
   ]
  },
  {
   "title": "Responses codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.http.post.workshop.status_code.*"
    }
   ]
  }
 ]
}